name: test
on:
  push:
    branches:
      - main
jobs:
  test:
    strategy:
      matrix:
        go-version: [ 1.16.x, 1.17.x, 1.19.x, 1.20.x, 1.21.x ] # Lowest supported and current stable versions.
    runs-on: ubuntu-latest
    steps:

      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Go cache
        uses: actions/cache@v3
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
          key: ${{ runner.os }}-go-cache-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-cache

      - name: Run gofmt
        run: gofmt -d -e . 2>&1 | tee outfile && test -z "$(cat outfile)" && rm outfile

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3

      - name: Run staticcheck
        if: matrix.go-version == '1.21.x'
        uses: dominikh/staticcheck-action@v1.3.0
        with:
          version: "2023.1.3"
          install-go: false
          cache-key: ${{ matrix.go }}

      - name: Run go vet
        run: |
          go vet ./...

      - name: Run go test
        run: |
          go test -v -race -coverprofile=coverage.txt -covermode=atomic ./...


      - name: Report on code coverage
        if: matrix.go-version == '1.21.x'
        uses: codecov/codecov-action@v3
        with:
          file: ./coverage.txt
